[build]
targets  = [
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
  "x86_64-apple-darwin",
  "aarch64-apple-darwin"
]
profiles   = ["release"]
signatures = false
changelog  = false

[archive]
formats = ["tar.gz", "zip"]

[assets]
include-binaries = true
files = [
  "README.md",
  "LICENSE",
]

[release]
publish    = true
draft      = false
prerelease = false

[dist]
build-command = "cargo build --release"

[ci.github]
runner = "ubuntu-latest"