[package]
name        = "cleansh"
version     = "0.1.0"
description = "Sanitize your terminal output. One tool. One purpose."
license     = "MIT"
repository  = "https://github.com/KarmaYama/cleansh"

[build]
profiles = ["release"]
signatures = false
changelog  = false

[archive]
formats = ["tar.gz", "zip"]
all-platforms = true

[assets]
include-binaries = true
files = [
  "README.md",
  "LICENSE",
]

[release]
publish = true
draft = false
prerelease = false
