name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cleansh_build:
    name: Build & Package for ${{ matrix.target }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          brew update
          brew install openssl@1.1 pkg-config

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Cache Cargo registry & build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install dist (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: cargo install cargo-dist --locked --force

      - name: Install dist (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: cargo install cargo-dist --locked --force

      - name: Verify dist binary (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "--- Verifying 'dist' binary ---"
          ls -lh ~/.cargo/bin/
          ~/.cargo/bin/dist --version

      - name: Verify dist binary (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "--- Verifying 'dist' binary ---"
          Get-Command dist -ErrorAction Stop
          dist --version

      - name: Build & package release (Unix)
        if: runner.os != 'Windows'
        shell: bash
        env:
          RUSTFLAGS: '-C target-cpu=native'
        run: |
          ~/.cargo/bin/dist build ${{ matrix.target }} \
            --tag ${{ github.ref_name }} \
            --ci github

      - name: Build & package release (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        env:
          RUSTFLAGS: '-C target-cpu=native'
        run: |
          dist build ${{ matrix.target }} `
            --tag ${{ github.ref_name }} `
            --ci github
