name: Release

on:
  push:
    # Build a release whenever a new tag matching v* is pushed.
    tags:
      - 'v*'
  workflow_dispatch:

env:
  # GitHub token for creating releases and uploading assets
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cleansh_build:
    name: Build & Package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install openssl@1.1 pkg-config

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Cache Cargo registry & build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install cargo-dist
        run: cargo install cargo-dist --locked

      - name: Verify cargo-dist
        run: |
          echo "PATH: $PATH"
          if ! command -v cargo-dist; then
            echo "Error: cargo-dist not found"
            exit 1
          fi
          if ! cargo dist --help | grep -q build; then
            echo "Error: 'cargo dist build' unavailable"
            exit 1
          fi

      - name: Build & package releases
        run: cargo dist build --tag ${{ github.ref_name }}
        env:
          RUSTFLAGS: '-C target-cpu=native'

  cleansh_upload:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    needs: cleansh_build
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install cargo-dist
        run: cargo install cargo-dist --locked

      - name: Verify cargo-dist
        run: |
          if ! command -v cargo-dist; then
            echo "Error: cargo-dist not found"
            exit 1
          fi

      - name: Upload release assets
        run: cargo dist upload --tag ${{ github.ref_name }}
