name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cleansh_build:
    name: Build & Package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Install system dependencies (macOS)
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          brew update
          brew install openssl@1.1 pkg-config

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev

      - name: Cache Cargo registry & build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ matrix.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ matrix.os }}-cargo-

      - name: Install dist (Unix)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: cargo install cargo-dist --locked --force

      - name: Install dist (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: cargo install cargo-dist --locked --force

      - name: Verify dist binary (Unix)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          echo "--- Verifying 'dist' binary ---"
          # Assuming ~/.cargo/bin is in PATH for direct 'dist' call
          dist --version

      - name: Verify dist binary (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          dist --version

      - name: Build & package release (Unix)
        if: matrix.os != 'windows-latest'
        shell: bash
        env:
          RUSTFLAGS: '-C target-cpu=native'
          MATRIX_OS: ${{ matrix.os }} # Pass matrix.os to an environment variable accessible within the shell script
        run: |
          TARGET_TRIPLE=""
          # Use the MATRIX_OS environment variable for conditional logic in Bash
          if [[ "$MATRIX_OS" == "macos-latest" ]]; then
            # Determine macOS architecture for the target triple
            if [[ "$(uname -m)" == "arm64" ]]; then
              TARGET_TRIPLE="aarch64-apple-darwin"
            else
              TARGET_TRIPLE="x86_64-apple-darwin"
            fi
          elif [[ "$MATRIX_OS" == "ubuntu-latest" ]]; then
            TARGET_TRIPLE="x86_64-unknown-linux-gnu"
          else
            echo "Error: Unsupported OS for Unix build: $MATRIX_OS"
            exit 1
          fi

          # Safety check: Ensure TARGET_TRIPLE is set
          if [[ -z "$TARGET_TRIPLE" ]]; then
            echo "Error: TARGET_TRIPLE is empty! Aborting dist build."
            exit 1
          fi

          # Optional: Detect and Print Final Target for clearer logs
          echo "Building for target: $TARGET_TRIPLE"

          # Explicitly provide the --target flag as cargo-dist demands it
          # Explicitly adding --artifacts all for clarity and robust packaging
          dist build \
            --tag ${{ github.ref_name }} \
            --ci github \
            --target "$TARGET_TRIPLE" \
            --artifacts all

      - name: Build & package release (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        env:
          RUSTFLAGS: '-C target-cpu=native'
        run: |
          $TARGET_TRIPLE = "x86_64-pc-windows-msvc" # Standard Windows target

          # Safety check: Ensure TARGET_TRIPLE is set (PowerShell syntax)
          if (-not $TARGET_TRIPLE) {
            Write-Error "TARGET_TRIPLE is empty. Aborting."
            exit 1
          }

          # Optional: Detect and Print Final Target for clearer logs
          Write-Host "Building for target: $TARGET_TRIPLE"

          # Explicitly provide the --target flag
          # Explicitly adding --artifacts all for clarity and robust packaging
          dist build `
            --tag ${{ github.ref_name }} `
            --ci github `
            --target $TARGET_TRIPLE `
            --artifacts all