name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  cleansh_build:
    name: Build & Package
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Install system dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install openssl@1.1 pkg-config
        shell: bash

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev
        shell: bash

      - name: Cache Cargo registry & build artifacts
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install cargo-dist (Unix)
        if: runner.os != 'Windows'
        run: |
          cargo install cargo-dist --locked --force
        shell: bash

      - name: Install cargo-dist (Windows)
        if: runner.os == 'Windows'
        run: |
          cargo install cargo-dist --locked --force
        shell: pwsh

      - name: Verify cargo-dist installation (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: |
          echo "--- Verifying cargo-dist binary ---"
          ls -l ~/.cargo/bin/
          ~/.cargo/bin/cargo-dist --version

      - name: Verify cargo-dist installation (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          Write-Host "--- Verifying cargo-dist binary ---"
          Get-Command cargo-dist -ErrorAction Stop
          cargo-dist --version

      - name: Build & package releases (Unix)
        if: runner.os != 'Windows'
        shell: bash
        run: ~/.cargo/bin/cargo-dist --tag ${{ github.ref_name }}
        env:
          RUSTFLAGS: '-C target-cpu=native'

      - name: Build & package releases (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: cargo-dist --tag ${{ github.ref_name }}
