# .github/workflows/rust.yml
name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test: # Renamed job to better reflect its purpose
    runs-on: ubuntu-latest
    permissions:
      contents: read # Only read permission is needed for checkout and running tests/rdme check

    steps:
      - uses: actions/checkout@v4

      # Install Rust toolchain (optional, but good practice if not guaranteed by runner)
      # The 'actions/checkout@v4' often includes Rust, but this ensures it.
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable # Ensures a stable Rust toolchain is available

      # Install cargo-rdme for README consistency check
      - name: Install cargo-rdme
        run: cargo install cargo-rdme

      # Check if README.md is up-to-date with lib.rs documentation
      # This step will fail the CI if README.md needs to be regenerated.
      - name: Check README.md consistency
        run: cargo rdme --check

      - name: Build
        run: cargo build --verbose

      - name: Run tests (including doc tests and skipping clipboard test in CI)
        run: cargo test --verbose